# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: default
  #vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: CmdLine@2
  displayName: 'Run Tosca CI'
  inputs:
    script: '$(Agent.HomeDirectory)\\_work\\Client\\ToscaCIClient.exe -m distributed -t junit -r $(Common.TestResultsDirectory)\\ToscaCI.xml'
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/ToscaCI*.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    failTaskOnFailedTests: true
    testRunTitle: 'Publish ToscaCI Test Results'
